## Data collection structures for Data Analytics

### Table of Contents
1. [Basic Structure](#basic-structure)
2. [Lists](#lists)
3. [Tuples](#tuples)
4. [Sets](#sets)
5. [Dictionaries](#dictionaries)
6. [Nested Structures](#nested-structures)
7. [Numpy Arrays](#numpy-arrays)
8. [Pandas Series and Dataframe](#pandas)

<a name="basic-structure"></a>
## 1. Basic Structure


In Data Analytics, Python data structures are the foundational building blocks for managing data. Choosing the right structure impacts performance, memory usage, and the ease of performing complex operations like filtering, aggregation, and mathematical computation.

<a name="lists"></a>
## 2. Lists
*Exploring list methods, repetition, and transformations.*

Lists are versatile, ordered collections used to store sequences of items. In analytics, they are often used for:
- Storing raw observation values.
- Maintaining a list of feature names or column headers.
- Collecting results from iterative processes or simulations.

In [13]:
# Traversing lists
list1 = [12, 11, 18, 24, 10, 5, 14, 55, 10, 29]

# Method 1: Loop
for i in range(len(list1)):
  print(f"Index {i}: {list1[i]}")

# Method 2: A more Pythonic way
print("\nTraversing List:")
for i in list1:
  print(i, end=", ")
print()

# List Comprehension
list2 = [i for i in range(1, 16)]
print("\nList 2:", list2)

even_list = [i for i in range(1, 16) if i % 2 == 0]
print("\nEven elements:", even_list)

odd_list = [i for i in range(1, 16) if i % 2 != 0]
print("Odd elements:", odd_list)

Index 0: 12
Index 1: 11
Index 2: 18
Index 3: 24
Index 4: 10
Index 5: 5
Index 6: 14
Index 7: 55
Index 8: 10
Index 9: 29

Traversing List:
12, 11, 18, 24, 10, 5, 14, 55, 10, 29, 

List 2: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

Even elements: [2, 4, 6, 8, 10, 12, 14]
Odd elements: [1, 3, 5, 7, 9, 11, 13, 15]


In [15]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
# Reverse the list using slicing
reversed_numbers = numbers[::-1]
print("Original list:", numbers)
print("Reversed list:", reversed_numbers)

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
numbers.reverse()
print("Reversed list:", numbers)

Original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Reversed list: [15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
Reversed list: [15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [19]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]
list3 = list1 + list2

print("List 1:", list1)
print("List 2:", list2)
print("Concatenated list:", list3)

list1 = ['Data', 'Analytics']
list2 = ['with', 'Python']
result = list1 + list2
print(result)

# Use join
result = ' '.join(result)
print(result)

List 1: [1, 2, 3, 4, 5]
List 2: [6, 7, 8, 9, 10]
Concatenated list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
['Data', 'Analytics', 'with', 'Python']
Data Analytics with Python


In [23]:
numbers = [1, 2, 3, 4, 5]
result = numbers * 3

print("Original list:", numbers)
print("Repeated list:", result)

numbers = [1, 2, 3]
print(numbers * 2)
print(numbers * 4)

numbers = [1, 2, 3, 4, 5]
print("Add by 4:", [i + 4 for i in numbers])
print("Multiplication by 3:", [i * 3 for i in numbers])

Original list: [1, 2, 3, 4, 5]
Repeated list: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 1, 2, 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
Add by 4: [5, 6, 7, 8, 9]
Multiplication by 3: [3, 6, 9, 12, 15]


In [30]:
numbers = [1, 2, 3, 4, 5]
numbers.append(6)
numbers.append([6, 7]) # [6, 7] is added as one element
print("Append:", numbers)

numbers = [1, 2, 3, 4, 5]
numbers.clear()
print(numbers)

numbers = [1, 2, 3, 4, 5]
numbers.extend([6, 7, 8])
print("Extend:", numbers)

numbers = [1, 2, 3, 4, 5]
# Here, 10 is inserted at index 2.
# The existing elements are shifted to the right.
numbers.insert(2, 10)
print("\nInsert:", numbers)

numbers = [1, 2, 3, 4, 5]
removed = numbers.pop(2)
print("Removed element:", removed)
print("Remaining list:", numbers)
removed = numbers.pop()
print("Removed element:", removed)
print("Remaining list:", numbers)

numbers = [1, 2, 3, 4, 3, 5]
numbers.remove(3)
print(numbers)

numbers = [1, 2, 3, 4, 5]
numbers.reverse()
print(numbers)

numbers = [12, 5, 1, 9, 3, 15, 7, 2, 11, 6]
numbers.sort()
print(numbers)

numbers.sort(reverse=True)
print(numbers)

names = ['James', 'Alice', 'David', 'Chris', 'Bob']
names.sort()
print(names)


numbers = [1, 2, 2, 3, 4, 2, 5, 2]
print("Number of 2s:", numbers.count(2))

numbers = [1, 2, 3, 3, 4, 5, 3, 6, 7, 3]
print("Number of 3s:", numbers.count(3))

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
print("Length of the list:", len(numbers))

numbers = [1, 2, 3, 4, 5]
print("Last element:", numbers[len(numbers) - 1])

Append: [1, 2, 3, 4, 5, 6, [6, 7]]
[]
Extend: [1, 2, 3, 4, 5, 6, 7, 8]

Insert: [1, 2, 10, 3, 4, 5]
Removed element: 3
Remaining list: [1, 2, 4, 5]
Removed element: 5
Remaining list: [1, 2, 4]
[1, 2, 4, 3, 5]
[5, 4, 3, 2, 1]
[1, 2, 3, 5, 6, 7, 9, 11, 12, 15]
[15, 12, 11, 9, 7, 6, 5, 3, 2, 1]
['Alice', 'Bob', 'Chris', 'David', 'James']
Number of 2s: 4
Number of 3s: 4
Length of the list: 15
Last element: 5


In [31]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
print("Sum:", sum(numbers))

numbers = [12, 5, 1, 14, 8, 3, 15, 7, 2, 11, 6, 10, 4, 13, 9]
print("Maximum value:", max(numbers))
print("Minimum value:", min(numbers))

Sum: 120
Maximum value: 15
Minimum value: 1


<a name="tuples"></a>
## 3. Tuples
*Working with immutable sequences.*

Tuples are immutable sequences, meaning their content cannot be changed after creation. In data workflows, they are used for:
- Storing fixed record data (e.g., a constant GPS coordinate or a fixed date).
- Ensuring data integrity where values should not be accidentally modified.
- Function return values that contain multiple distinct pieces of information.

In [32]:
# Create a tuple
numbers = (1, 2, 3, 4, 5)
print("Tuple:", numbers)
print("Length:", len(numbers))
print("Sum:", sum(numbers))
print("Maximum:", max(numbers))
print("Minimum:", min(numbers))

# Convert tuple to list
numbers_list = list(numbers)

# Add an element
numbers_list.append(6)

# Convert back to tuple
numbers = tuple(numbers_list)
print("After adding 6:", numbers)

Tuple: (1, 2, 3, 4, 5)
Length: 5
Sum: 15
Maximum: 5
Minimum: 1
After adding 6: (1, 2, 3, 4, 5, 6)


<a name="sets"></a>
## 4. Sets
*Unordered collections of unique elements and set operations.*

Sets are unordered collections of unique elements. They are powerful for analytics tasks involving:
- Finding unique values in a dataset (de-duplication).
- Set algebra (Union, Intersection, Difference) to compare different customer segments or product IDs.
- Membership testing (checking if an ID exists in a whitelist/blacklist) which is faster in sets than in lists.

In [34]:
# Create a set
numbers = {1, 2, 3, 4, 5}
print("Set:", numbers)

# Add an element
numbers.add(6)
print("After add:", numbers)

# Remove an element
numbers.remove(6)
print("After remove:", numbers)

# Add multiple elements
numbers.update([6, 7, 8])
print("After update:", numbers)

# Set operations
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
print("Difference:", set1.difference(set2))
print("Intersection:", set1.intersection(set2))
print("Union:", set1.union(set2))
print("Disjoint:", set1.isdisjoint(set2))

# Subset and superset
small_set = {1, 2, 3}
print("Subset:", small_set.issubset(set1))
print("Superset:", set1.issuperset(small_set))

# Built-in functions
print("Length:", len(set1))
print("Sum:", sum(set1))
print("Maximum:", max(set1))
print("Minimum:", min(set1))

Set: {1, 2, 3, 4, 5}
After add: {1, 2, 3, 4, 5, 6}
After remove: {1, 2, 3, 4, 5}
After update: {1, 2, 3, 4, 5, 6, 7, 8}
Difference: {1, 2, 3}
Intersection: {4, 5}
Union: {1, 2, 3, 4, 5, 6, 7, 8}
Disjoint: False
Subset: True
Superset: True
Length: 5
Sum: 15
Maximum: 5
Minimum: 1


<a name="dictionaries"></a>
## 5. Dictionaries
*Key-value pair mappings and common dictionary methods.*

Dictionaries store data in key-value pairs, providing highly efficient lookups. In Data Analytics, they are essential for:
- Mapping values (e.g., encoding categorical strings to numeric values).
- Storing configuration parameters for models.
- Representing JSON-like data or row-based records where labels are necessary.

In [36]:
# Create a dictionary
months = { "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4,
          "May": 5, "Jun": 6, "Jul": 7, "Aug": 8,
           "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12 }

print("Dictionary:", months)
print("Keys:", months.keys())
print("Values:", months.values())
print("Items:", months.items())
print("February:", months.get("Feb"))

new_months = dict.fromkeys(["Jun", "Jul", "Aug"], 0)
print("From keys:", new_months)

removed = months.pop("Dec")
print("Removed value:", removed)
print("After pop:", months)

removed_item = months.popitem()
print("Removed item:", removed_item)
print("After popitem:", months)

value = months.setdefault("Dec", 12)
print("December:", value)
print("After setdefault:", months)

months.update({"Dec": 12})
print("After update:", months)

print("Number of keys:", len(months.keys()))
print("Number of values:", len(months.values()))

number_months = { 1: 11, 2: 24, 3: 31,
                 4: 49, 5: 54,
                  6: 63, 7: 72, 8: 82,
                  9: 91, 10: 102,
                  11: 114, 12: 122}

print("Sum of keys:", sum(number_months.keys()))
print("Sum of values:", sum(number_months.values()))

Dictionary: {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6, 'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12}
Keys: dict_keys(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
Values: dict_values([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
Items: dict_items([('Jan', 1), ('Feb', 2), ('Mar', 3), ('Apr', 4), ('May', 5), ('Jun', 6), ('Jul', 7), ('Aug', 8), ('Sep', 9), ('Oct', 10), ('Nov', 11), ('Dec', 12)])
February: 2
From keys: {'Jun': 0, 'Jul': 0, 'Aug': 0}
Removed value: 12
After pop: {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6, 'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11}
Removed item: ('Nov', 11)
After popitem: {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6, 'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10}
December: 12
After setdefault: {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6, 'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Dec': 12}
After update: {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr':

<a name="nested-structures"></a>
## 6. Nested Structures
*Combining lists, tuples, and dictionaries for complex data.*

Nested structures allow for representing complex, multi-dimensional data. This is common when dealing with:
- Hierarchical data like organizational structures.
- Result sets from databases or APIs where a row is a list/tuple and the entire table is a list.
- Grouped data where a dictionary key points to a list of observations.

In [41]:
# List of Lists
students = [ ["Alice", 20, 85], ["Bob", 21, 90],
 ["Charlie", 19, 78] ]

print(students)
print(students[0])
print(students[0][1])

# List of Tuples
students = [ ("Alice", 20, "Computer Science"),
 ("Bob", 21, "Data Science"), ("Charlie", 19, "Information Technology") ]

print(students)
print(students[0])
print(students[0][2])

# Dictionary of lists
students = { "Alice": [20, 85, 90], "Bob": [21, 90, 88],
            "Charlie": [19, 78, 85] }

print(students)
print(students["Alice"])
print(students["Alice"][1])


# Dictionary of dictionaries
students = { "Alice": {"age": 20, "score": 85, "major": "Computer Science" },
            "Bob": { "age": 21, "score": 90, "major": "Data Science" } }

print(students)
print(students["Alice"])
print(students["Alice"]["major"])

[['Alice', 20, 85], ['Bob', 21, 90], ['Charlie', 19, 78]]
['Alice', 20, 85]
20
[('Alice', 20, 'Computer Science'), ('Bob', 21, 'Data Science'), ('Charlie', 19, 'Information Technology')]
('Alice', 20, 'Computer Science')
Computer Science
{'Alice': [20, 85, 90], 'Bob': [21, 90, 88], 'Charlie': [19, 78, 85]}
[20, 85, 90]
85
{'Alice': {'age': 20, 'score': 85, 'major': 'Computer Science'}, 'Bob': {'age': 21, 'score': 90, 'major': 'Data Science'}}
{'age': 20, 'score': 85, 'major': 'Computer Science'}
Computer Science


<a name="numpy-arrays"></a>
## 7. Numpy Arrays
*Introduction to high-performance multidimensional arrays.*

NumPy arrays are the standard for numerical computing in Python. Unlike standard lists, NumPy arrays:
- Are memory-efficient and allow for vectorized operations (applying math to an entire array at once).
- Form the basis of most Machine Learning libraries.
- Are used for handling matrices in linear algebra and statistical modeling.

In [42]:
import numpy as np

numbers = [1, 2, 3, 4, 5]
array = np.array(numbers)

print(array)

[1 2 3 4 5]


In [43]:
matrix = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<a name="pandas"></a>
## 8. Pandas Series and Dataframe
*Essential tools for tabular data analysis.*

Pandas is the primary library for data manipulation.
- **Series**: 1D labeled arrays, representing a single column or row.
- **DataFrames**: 2D labeled structures, similar to Excel spreadsheets or SQL tables.
These structures provide advanced methods for handling missing data, joining datasets, and time-series analysis.

In [44]:
import pandas as pd

scores = [85, 90, 78, 92, 88]
series = pd.Series(scores)

print(series)

0    85
1    90
2    78
3    92
4    88
dtype: int64


In [45]:
scores = { "Alice": 85, "Bob": 90, "Charlie": 78 }
series = pd.Series(scores)

print(series)

Alice      85
Bob        90
Charlie    78
dtype: int64


In [46]:
data = { "Name": ["Alice", "Bob", "Charlie"],
        "Age": [20, 21, 19],
         "Score": [85, 90, 78] }

df = pd.DataFrame(data)
print(df)

      Name  Age  Score
0    Alice   20     85
1      Bob   21     90
2  Charlie   19     78
